### ISSUE TITLE
SwitchSchedules why is it a Type number?

### ISSUE THREAD

**Issue by DasNordlicht** [smart-data-models/dataModel.EnergyCIM#1]
I would expect SwitchSchedules to have an ID to an entity of the
data model SwitchSchedules but not a number.

`    SwitchSchedules:    
      description: 'A SwitchSchedule is associated with a Switch. Default: ''list'''    
      type: number    
      x-ngsi:    
        model: https://schema.org/Number    
`

**Comment by albertoabellagarcia** [comment]
This could be an error of the automatic script making the conversion from the original python classes. do you have an example where SwitchSchedule is a string?

**Comment by FR-ADDIX** [comment]
Unfortunately, I don't have a concrete example.
But when I assign a schedule to a switch I need the ID of the entity in which this schedule is mapped.

**Comment by albertoabellagarcia** [comment]
Fixed. updated documentation, ddbb, context, etc

**Comment by VladimirAlexiev** [comment]
@albertoabellagarcia: the SwitchSchedules prop should neither be a number nor a string. It should be an array of these objects: https://github.com/smart-data-models/dataModel.EnergyCIM/tree/master/SwitchSchedule.

In JSON you must make a choice whether the prop should carry embedded JSON objects, or references to them (URLs).
In RDF you are not forced to such a choice: it's always a reference (even if the sub-object doesn't have a URL but is a blank node).
What is the stance of SmartModels regarding embedding vs referencing?
