### ISSUE TITLE
fatal modeling flaws

### ISSUE THREAD

**Issue by VladimirAlexiev** [smart-data-models/dataModel.EnergyCIM#3]
@albertoabellagarcia 
Look at https://github.com/smart-data-models/dataModel.EnergyCIM/blob/master/ACDCConverterDCTerminal/doc/spec.md, and compare it to the official ontological definition, eg `IEC61970-600-2_CGMES_3_0_0_RDFS_501Ed2CD_EQ.ttl` . 
There are a number of modeling flaws that I would say are fatal and make the SmartModel so far from the original model as to be unusable:

1. It has a number of useless generic props like `address[object]`. I can assure you that an electrical terminal doesn't have a street address!
2. Object props like `DCConductingEquipment` are represented as `[number]` which is wrong. https://github.com/smart-data-models/dataModel.EnergyCIM/issues/1 describes a similar issue (cc @DasNordlicht). This should be an object reference: neither number nor string.
3. Props that hold an enumerated value eg `polarity` are also represented as `[number]`. Again, this is wrong, since the original prop has range `DCPolarityKind` that is a class grouping enumeration values (resources) like `cim:DCPolarityKind.positive`. (Despite the wrong declaration of the original prop as `owl:DatatypeProperty`)
4. It doesn't follow the class hierarchy. Eg `ACDCConverterDCTerminal<DCBaseTerminal<ACDCTerminal`, and `ACDCConverterDCTerminal` must inherit the props of its parent classes, such as:
   - `DCNode` "The DC connectivity node to which this DC base terminal connects with zero impedance" from `DCBaseTerminal`
   - `BusNameMarker, OperationalLimitSet` from `ACDCTerminal`

**Comment by albertoabellagarcia** [comment]
1.- the models have extra attributes but you do not need to use them if you do not need them. Just ignore them. 

2.- You are right about the data types. As long as we do not have examples there are errors. glad to assign the right one if you have one example

3.- Same as 2.

4.- No it does not follow the class hierarchy. In fact there is no hierarchy in SDM. You can link one data model with other but it does not mean that you have a hierarchical relationship. if there are missing attributes we need to copy them.  You can think that this is not very practical but our experience is that this is not a relevant issue. Users like to have all attributes in the model and do not need to follow relationships to know what is really in their model.  

we are glad to fix everything that you provide preferably with an example payload. 

thank you very much

**Comment by VladimirAlexiev** [comment]
@albertoabellagarcia What sources did you use to make your model?
You can find the resources you asked for at https://www.entsoe.eu/data/cim/cim-conformity-and-interoperability/:
- Sample data is in https://www.entsoe.eu/Documents/CIM_documents/Grid_Model_CIM/ENTSO-E_Test_Configurations_v3.0.2.zip (use `FullGrid` and `RealGrid`)
- RDFS and SHACL schemas are in https://www.entsoe.eu/Documents/CIM_documents/Grid_Model_CIM/IEC61970-600-2_CGMES_3_0_1_ApplicationProfiles.zip (use `RDFSEd2Beta`)

Commenting back on the issues I raised:
1. Superfluous attributes are nearly as harmful as missed attributes. They are confusing and may mislead a user in putting data in the wrong fields. And how do you guarantee there's no conflict between your superfluous attributes and mandated attributes? 
Just curious: how did you decide that every RDF resource may have an `Address`?
2. The RDFS ontology defines all ranges clearly, eg:
```ttl
cim:ACDCConverterDCTerminal.DCConductingEquipment
        rdf:type         owl:ObjectProperty ;
        rdfs:domain      cim:ACDCConverterDCTerminal ;
        rdfs:label       "DCConductingEquipment"@en ;
        rdfs:range       cim:ACDCConverter ;
        owl:inverseOf    cim:ACDCConverter.DCTerminals ;
        skos:definition  "A DC converter terminal belong to an DC converter."@en .
```
3. Same here, the ontology clearly defines the enumeration classes and all their members:
```ttl
cim:ACDCConverterDCTerminal.polarity
        rdfs:range       cim:DCPolarityKind .

cim:DCPolarityKind  rdf:type  owl:Class ;
        rdfs:label       "DCPolarityKind"@en ;
        rdfs:subClassOf  cim:Enumeration ;
        eq:Package       "Package_CoreEquipmentProfile" ;
        owl:oneOf        ( cim:DCPolarityKind.positive cim:DCPolarityKind.middle cim:DCPolarityKind.negative ) ;
        skos:definition  "Polarity for DC circuits."@en .

cim:DCPolarityKind.middle
        rdf:type         owl:NamedIndividual , owl:Thing ;
        rdfs:domain      cim:DCPolarityKind ;
        rdfs:label       "middle "@en ;
        eq:isenum        "True" ;
        skos:definition  "Middle pole. The converter terminal is the midpoint in a bipolar or symmetric monopole configuration. The midpoint can be grounded and/or have a metallic return."@en .
```
4. "there is no hierarchy in SDM": then I don't think it's an adequate "polyglot modeling" method. Most schema languages (certainly ontologies) allow inheritance. See https://github.com/w3c-ccg/traceability-vocab/issues/296 for some thoughts.
"if there are missing attributes we need to copy them": well, do it then!
5. "we are glad to fix everything that you provide": do you mean I need to report every single problem generated by your tooling? I don't know how you generate your models, but I have pointed out generic (systemic) problems.
